name: Integration tests with proxy

on:
  push:
    branches:
      - $default-branch
      - development
      - master
    paths-ignore:
      - varia/**
      - '**.md'
      - utils/prepare_rpm.sh
      - .github/workflows/publish.yml
  schedule:
      # We run the integration tests daily. These tests depend on external hosts and certificates
      # and it's useful to know when something is not working as soon as possible
      #
      # * is a special character in YAML so you have to quote this string
      - cron:  '42 7 * * *'
  # Run tests for any PRs
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  ##############################################################################
  # macOS

  macos:
    name: Running integration tests on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-11
          - macos-12
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:

      - name: Git clone repository
        uses: actions/checkout@v3

      - name: Install shellcheck
        run: brew install shellcheck shunit2 bash-completion nmap tinyproxy

      - name: install cpanm and Date::Parse
        uses: perl-actions/install-with-cpanm@v1
        with:
          install: Date::Parse

      - name: Run the integration tests
        run:  |
          uname -a \
          && make integration_tests \
          && bash -c "source ./check_ssl_cert.completion && complete -p check_ssl_cert" \
          && make dist \
          && sudo make install_bash_completion && bash -c "source ./check_ssl_cert.completion && complete -p check_ssl_cert" \
          && if command -v shellcheck > /dev/null 2>&1  ; then shellcheck ./check_ssl_cert test/*.sh ; fi


  ##############################################################################
  # Linuxes

  linux:
    # The host should always be linux
    runs-on: ubuntu-latest
    name: Running integration tests on ${{ matrix.distro }}
    strategy:
      fail-fast: false
      matrix:
        distro:
          - 'debian:10'
          - 'debian:11'
        include:

          - distro: 'debian:10'
            pre: >-
              apt-get update &&
              DEBIAN_FRONTEND=noninteractive apt-get -y install nmap shellcheck curl sudo perl make bzip2 file openssl dnsutils shunit2 man bc bash-completion default-jre tinyproxy
          - distro: 'debian:11'
            pre: >-
              apt-get update &&
              DEBIAN_FRONTEND=noninteractive apt-get -y install nmap shellcheck curl sudo perl make bzip2 file openssl dnsutils shunit2 man bc bash-completion iproute2 default-jre tinyproxy
z
    steps:

      - name: Git clone repository
        uses: actions/checkout@v3

      - name: Run the integration tests on ${{ matrix.distro }}
        env:
          PRE: ${{ matrix.pre }}
        run: |
          echo $PRE > ./prep-cmd.sh
          docker run --network host -w /check_ssl_cert -v ${PWD}:/check_ssl_cert ${{ matrix.distro }} \
              /bin/sh -c 'sh ./prep-cmd.sh \
              && curl -L https://cpanmin.us | sudo perl - --sudo App::cpanminus \
              && cpanm --sudo install Date::Parse \
              && uname -a \
              && make integration_tests \
              && bash -c "source ./check_ssl_cert.completion && complete -p check_ssl_cert" \
              && make dist \
              && sudo make install_bash_completion && bash -c "source ./check_ssl_cert.completion && complete -p check_ssl_cert" \
              && if command -v shellcheck > /dev/null 2>&1  ; then shellcheck ./check_ssl_cert test/*.sh ; fi'
z
